// import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
// import { Database } from '@/types/supabase';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const supabase = createClientComponentClient<Database>();

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
